# To utilize the default config system built in the compat system image, this file is required. It defines the *structure* of the configuration file. These structured options display as changeable UI elements within the "Config" section of the service details page in the Embassy UI

tor-address:
  name: Network Tor Address
  description: The Tor address for the network interface. 
  type: pointer
  subtype: package
  package-id: sensei
  target: tor-address
  interface: main
lan-address:
  name: Network LAN Address
  description: The LAN address for the network interface. 
  type: pointer
  subtype: package
  package-id: sensei
  target: lan-address
  interface: main
bitcoind:
  type: union
  name: Bitcoin
  description: The Bitcoin node to connect to
  tag:
    id: type
    name: Type
    description: |
      - Bitcoin Core: The Bitcoin Core service installed to your Embassy
      - Bitcoin Proxy: The Bitcoin Proxy service installed on your Embassy
    variant-names:
      internal: Bitcoin Core
      internal-proxy: Bitcoin Proxy
  default: internal-proxy
  variants:
    internal:
      user:
        type: pointer
        name: RPC Username
        description: The username for the RPC user for Bitcoin Core
        subtype: package
        package-id: bitcoind
        target: config
        selector: "$.rpc.username"
        multi: false
      password:
        type: pointer
        name: RPC Password
        description: The password for the RPC user for Bitcoin Core
        subtype: package
        package-id: bitcoind
        target: config
        selector: "$.rpc.password"
        multi: false
    internal-proxy:
      user:
        type: pointer
        name: RPC Username
        description: The username for the RPC user allocated to Mempool
        subtype: package
        package-id: btc-rpc-proxy
        target: config
        multi: false
        selector: '$.users.[?(@.name == "mempool")].name'
      password:
        type: pointer
        name: RPC Password
        description: The password for the RPC user allocated to Mempool
        subtype: package
        package-id: btc-rpc-proxy
        target: config
        multi: false
        selector: '$.users.[?(@.name == "mempool")].password'